spring.application.name=Backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/krishiAI
spring.datasource.username=${SQL_USERNAME}
spring.datasource.password=${SQL_PASSWORD}

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

#JWT Configuration
jwt.secret=KrishiAISecretKeyForJwtAuthentication2026VerySecure
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587

spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
brevo.api.key=${BREVO_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp
brevo.sender.email=${BREVO_FROM_EMAIL}

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.debug=true
logging.level.org.eclipse.angus.mail=DEBUG

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# AI Service Configuration
ai.service.url=http://localhost:8000